### ISSUE TITLE
Clicking on Growl notification does not open email

### ISSUE THREAD

**Issue by michalkopanski** [fujifish/gmail-app#1]
After clicking on the Growl notification, the Gmail window is focused, and an alert displays for "Turn off popup blocker". After clicking "ok", the Gmail screen goes white.

OSX 10.11.6

**Comment by fujifish** [comment]
Updated to electron 1.3.5 to use node v6.
After pulling the fix, `npm install` with node v6, then run `npm run build`.
You might need to run `electron-rebuild --version 1.3.5` if you encounter problems after switching to the new version.

**Comment by michalkopanski** [comment]
Hi @fujifish, sorry for the delay. Thanks for this fix! Just wanted to confirm that the error message no longer appears.

Wondering if there would be a way to view the message when clicking on the Growl notification. Is that a feature enhancement you've considered adding?

**Comment by fujifish** [comment]
I haven't, but I'll take a look to see what's involved.

BTW, if you like this app I also created a google calendar app that works pretty much the same as the gmail-app...
